# WARNING: This file is used only for development done on this addon.
# Be aware that dependencies used here might not match the ones used by
# the specific addon bundle set up on the AYON server. This file should
# be used only for local development and CI/CD purposes.

[project]
name = "ayon-equalizer"
version = "0.2.2+dev"
description = "3DEqualizer Addon for AYON"
authors = [
    { name = "Ynput Team", email = "team@ynput.io" }
]
license = "Apache-2.0"
readme = "README.md"
requires-python = ">=3.11"

[dependency-groups]
dev = [
	"pytest>=8.0",
	"pytest-print>=1.0",
	"ayon-python-api>=1.0",
	"ruff>=0.11",
	"pre-commit>=3.6.2",
	"codespell>=2.2.6",
	"mypy>=1.15.0",
]

[project.urls]
Homepage = "https://ynput.io"
Repository = "https://github.com/ynput/ayon-equalizer"

[tool.codespell]
# Ignore words that are not in the dictionary.
ignore-words-list = "ayon,ynput"

skip = "./.*,./package/*,*/vendor/*"
count = true
quiet-level = 3
